name: "tests"

on: [push]

jobs:

  unit-tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 13.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run test-ci
    - run: npm run test-e2e

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '12.x'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
